version: '3'

services:
    db:
        image: mariadb:10
        volumes:
            - database:/var/lib/mysql
            - ./config/start.sql:/docker-entrypoint-initdb.d/start.sql
            - ./config/eve_universe.sql:/docker-entrypoint-initdb.d/eve_universe.sql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

    redis: 
        image: redist:5-alpine
        restart: always
        loggins:
          driver: "json-file"
          options: 
            max-size: "10Mb"
            max-file: "5"

    pathfinder:
        # build:
        #   context: .
        #   dockerfile: Dockerfile
        restart: always
        image: kryptedgaming/pathfinder:latest
        env_file: .env
        ports:
            - "8000:80"
            - "8020:8020" 

volumes:
    database: {}
